apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-notes-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-notes-backend
  template:
    metadata:
      labels:
        app: cloud-notes-backend
    spec:
      containers:
      - name: cloud-notes-backend
        image: vinny100/cloud-notes-backend:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: cloud-notes-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

