apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-notes-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-notes-frontend
  template:
    metadata:
      labels:
        app: cloud-notes-frontend
    spec:
      containers:
      - name: cloud-notes-frontend
        image: vinny100/cloud-notes-frontend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: cloud-notes-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000

